/**
 * Generated by tsnapi — public API snapshot of `@devframes/nuxt`
 */
// #region Interfaces
export interface DevframeNuxtModuleOptions {
  baseURL?: string;
  skipAppDefaults?: boolean;
  devframe?: DevframeDefinition;
  devMiddleware?: boolean | {
    port?: number;
    host?: string;
    flags?: Record<string, unknown>;
  };
}
// #endregion

// #region Default Export
declare const _default: NuxtModule<TOptions, TOptions, false>;
export default _default
// #endregion