/**
 * Generated by tsnapi — public API snapshot of `devframe/helpers/vite`
 */
// #region Interfaces
export interface ViteDevBridgeOptions {
  base?: string;
  devMiddleware?: boolean | {
    port?: number;
    host?: string;
    flags?: Record<string, unknown>;
  };
}
export interface DevframeVitePlugin {
  name: string;
  apply: 'serve';
  configureServer: (_: {
    middlewares: {
      use: (_: string, _: any) => void;
    };
    httpServer?: {
      once: (_: 'close', _: () => void) => void;
    } | null;
  }) => void | Promise<void>;
  closeBundle?: () => void | Promise<void>;
}
// #endregion

// #region Functions
export declare function viteDevBridge(_: DevframeDefinition, _?: ViteDevBridgeOptions): DevframeVitePlugin;
// #endregion