/**
 * Generated by tsnapi — public API snapshot of `devframe/rpc/transports/ws-client`
 */
// #region Interfaces
export interface WsRpcChannelOptions {
  url: string;
  onConnected?: (_: Event) => void;
  onError?: (_: Error) => void;
  onDisconnected?: (_: CloseEvent) => void;
  authToken?: string;
  definitions?: ReadonlyMap<string, Pick<RpcFunctionDefinitionAny, 'jsonSerializable'>>;
}
// #endregion

// #region Functions
export declare function createWsRpcChannel(_: WsRpcChannelOptions): ChannelOptions;
// #endregion