/**
 * Generated by tsnapi — public API snapshot of `devframe/types`
 */
// #region Other
export { AgentHandle }
export { AgentManifest }
export { AgentResource }
export { AgentResourceContent }
export { AgentResourceInput }
export { AgentTool }
export { AgentToolInput }
export { ConnectionMeta }
export { defineDevframe }
export { DevframeBrowserContext }
export { DevframeCliOptions }
export { DevframeDefinition }
export { DevframeDeploymentKind }
export { DevframeRuntime }
export { DevframeSetupInfo }
export { DevframeSpaOptions }
export { DevToolsAgentHost }
export { DevToolsAgentHostEvents }
export { DevToolsCapabilities }
export { DevToolsDiagnosticsDefinition }
export { DevToolsDiagnosticsHost }
export { DevToolsDiagnosticsLogger }
export { DevToolsHost }
export { DevToolsNodeContext }
export { DevToolsNodeRpcSession }
export { DevToolsNodeRpcSessionMeta }
export { DevToolsRpcClientFunctions }
export { DevToolsRpcServerFunctions }
export { DevToolsRpcSharedStates }
export { DevToolsViewHost }
export { EntriesToObject }
export { EventEmitter }
export { EventsMap }
export { EventUnsubscribe }
export { PartialWithoutId }
export { RpcBroadcastOptions }
export { RpcFunctionAgentOptions }
export { RpcFunctionsHost }
export { RpcSharedStateGetOptions }
export { RpcSharedStateHost }
export { RpcStreamingChannel }
export { RpcStreamingChannelOptions }
export { RpcStreamingHost }
export { Thenable }
// #endregion